LOG_DIR: "./exps/"
FRAME_IDXS: [0, ]

CHECKPOINT:
  EVERY_N_TRAIN_STEPS: 0
  EVERY_N_EPOCHS: 2

TRAINER:
  NAME: 'TemporalStereo'
  NUM_GPUS: 1
  VERSION: "sceneflow/first_try"
  MAX_EPOCHS: 40
  CHECK_VAL_EVERY_N_EPOCHS: 2

SCHEDULER:
  TYPE: 'MultiStepLR'
  MULTI_STEP_LR:
    MILESTONES: [30, 40]
    GAMMA: 0.1

OPTIMIZER:
  TYPE: 'RMSProp'
  RMSPROP:
    LR: 1e-3

MODEL:
  WITH_PREVIOUS: False
  PREVIOUS_WITH_GRADIENT: False
  WITH_FLOW: False
  USE_LOCAL_MAP: False
  LOCAL_MAP_SIZE: 0
  VIS_FEATURE: False
  BACKBONE:
    NAME: "TEMPORALSTEREO"
    IN_PLANES: 3
  AGGREGATION:
    NAME: "TEMPORALSTEREO"
    COARSE:
      IN_PLANES: 256
      C: 32
      NUM_SAMPLE: 12
      DELTA: 1.0
      BLOCK_COST_SCALE: 3
      TOPK: 2
      SPATIAL_FUSION: True
    FINE:
      IN_PLANES: 128
      C: 16
      NUM_SAMPLE: 5
      DELTA: 1.0
      BLOCK_COST_SCALE: 3
      TOPK: 2
      SPATIAL_FUSION: True
    PRECISE:
      IN_PLANES: 64
      C: 8
      NUM_SAMPLE: 5
      DELTA: 1.0
      BLOCK_COST_SCALE: 3
      TOPK: 2
  LOSSES:
    SMOOTH_L1_LOSS:
      GLOBAL_WEIGHT: 1.0
      WEIGHTS: [2.0, 1.0, 0.7, 0.5]
    WARSSERSTEIN_DISTANCE_LOSS:
      GLOBAL_WEIGHT: 2.0
      WEIGHTS: [1.0, 0.7, 0.5]

DATA:
  TRAIN:
    DATA_ROOT: "./datasets/SceneFlow/FlyingThings3D/"
    ANNFILE: "./splits/flyingthings3d/train.json"
    TYPE: 'SceneFlow'
    HEIGHT: 512
    WIDTH: 960
    DO_SAME_LR_TRANSFORM: False
    BATCH_SIZE: 4
    NUM_WORKERS: 4
    FRAME_IDXS: [0, ]
  VAL:
    DATA_ROOT: "./datasets/SceneFlow/FlyingThings3D/"
    ANNFILE: "./splits/flyingthings3d/test.json"
    TYPE: 'SceneFlow'
    HEIGHT: 544
    WIDTH: 960
    DO_SAME_LR_TRANSFORM: True
    BATCH_SIZE: 4
    NUM_WORKERS: 4
    FRAME_IDXS: [0, ]
  TEST:
    DATA_ROOT: "./datasets/SceneFlow/FlyingThings3D/"
    ANNFILE: "./splits/flyingthings3d/test.json"
    TYPE: 'SceneFlow'
    HEIGHT: 544
    WIDTH: 960
    DO_SAME_LR_TRANSFORM: True
    BATCH_SIZE: 1
    NUM_WORKERS: 4
    FRAME_IDXS: [0, ]

VAL:
  EVAL_DISPARITY_IDS: [0, 1, 2, 3, 4, 5, 6]
  VIS_INTERVAL: 8

